In [40]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
import scipy.signal

In [2]:
x = np.asarray([1, 2, 3, 0, 0, 0, 4, 5, 6])

## Convolve

In [3]:
np.convolve(x,x[::-1])

array([ 6, 17, 32, 23, 12,  0, 27, 58, 91, 58, 27,  0, 12, 23, 32, 17,  6])

## 1D FFT

In [9]:
x1 = np.append(x,np.zeros_like(x))

print np.round(np.fft.fftshift(np.abs(np.fft.ifft(np.abs(np.fft.fft(x1))**2))),decimals=0)

[ 0.  6. 17. 32. 23. 12.  0. 27. 58. 91. 58. 27.  0. 12. 23. 32. 17.  6.]


## 2D FFT

In [18]:
x2d = x.reshape(-1,3)[::2]
x2d_zp = np.hstack((x2d,np.zeros_like(x2d)))
x2d_zp = np.vstack((x2d_zp, np.zeros_like(x2d_zp)))

print x2d_zp

[[1 2 3 0 0 0]
 [4 5 6 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [27]:
np.round(np.fft.fftshift(np.abs(np.fft.ifft2(np.abs(np.fft.fft2(x2d_zp))**2))),decimals=0)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  6., 17., 32., 23., 12.],
       [ 0., 27., 58., 91., 58., 27.],
       [ 0., 12., 23., 32., 17.,  6.]])

In [46]:
scipy.signal.convolve2d(x2d,x2d[::-1,::-1])

array([[ 6, 17, 32, 23, 12],
       [27, 58, 91, 58, 27],
       [12, 23, 32, 17,  6]])

## 2D FFTs in terms of 1D FFTs

1. 1D FFT the rows
2. 1D FFT the columns from the previous step

In [32]:
np.round(np.abs(np.fft.fft([1,2,3,0,0,0])),decimals=2)

array([6.  , 4.36, 1.73, 2.  , 1.73, 4.36])

In [30]:
np.round(np.abs(np.fft.fft(x2d_zp)),decimals=2)

array([[ 6.  ,  4.36,  1.73,  2.  ,  1.73,  4.36],
       [15.  , 10.15,  1.73,  5.  ,  1.73, 10.15],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ]])

In [36]:
Fx2d = np.transpose(np.fft.fft(np.transpose(np.fft.fft(x2d_zp))))

In [38]:
np.all(np.isclose(Fx2d, np.fft.fft2(x2d_zp)))

True

# Hexagons!

In [54]:
h = np.array([np.asarray([1,2]),np.asarray([3,4,5]),np.asarray([6,7])])
h

array([array([1, 2]), array([3, 4, 5]), array([6, 7])], dtype=object)

In [55]:
h = np.asarray([[0,1,0,2,0],[3,0,4,0,5],[0,6,0,7,0]])
h

array([[0, 1, 0, 2, 0],
       [3, 0, 4, 0, 5],
       [0, 6, 0, 7, 0]])

In [56]:
scipy.signal.convolve2d(h,h[::-1,::-1])

array([[  0,   0,   7,   0,  20,   0,  12,   0,   0],
       [  0,  26,   0,  60,   0,  70,   0,  36,   0],
       [ 15,   0,  76,   0, 140,   0,  76,   0,  15],
       [  0,  36,   0,  70,   0,  60,   0,  26,   0],
       [  0,   0,  12,   0,  20,   0,   7,   0,   0]])

## 3D FFTs

1. 1D FFT in x
2. 1D FFT step-1 in y
3. 1D FFT step-2 in z